on: [push]

jobs:
  fargate-test:
    runs-on: ubuntu-latest
    name: Retrieve public IPs
    steps:
      - name: fargate-helper
        id: fargate
        uses: beinit/action-helper@v1
        with:
          cluster: arn:aws:ecs:us-east-2:481218820000:cluster/Dola-Qa-Fargate
          region: us-east-2
          serverGroup: platform-qa
          telemetryGroup: telemetry-qa
          configGroup: Dola-configs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: print the output
        run: echo "Server IP ${{ steps.fargate.server }}"
